ALTER TABLE "ContentIdea" ADD COLUMN "platform" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentIdea" ADD COLUMN "goal" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentIdea" ADD COLUMN "artCardText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentIdea" ADD COLUMN "caption" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentIdea" ADD COLUMN "cta" TEXT NOT NULL DEFAULT '';
ALTER TABLE "ContentIdea" ADD COLUMN "seoKeywords" TEXT NOT NULL DEFAULT '';
